/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package magicsquare;

import exceptions.*;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class AppTest {
	@Test
	public void testArgumentProcessing () {
		App app = new App();
		assertThrows(InvalidArgumentException.class, () -> app.processArgs(new String[0]));
		assertThrows(InvalidArgumentException.class, () -> app.processArgs(new String[2]));
	}
}
